### ISSUE TITLE
Frontend Backend Integration

### ISSUE THREAD

**Issue by betsybaileyy** [fenil29/employee-management-system-backend-node#9]
This is a great app. Could you please provide more details on how to integrate backend with frontend? Thanks in advance!

**Comment by fenil29** [comment]
frontend application is running on port 3000
backend application is running on port 4000

frontend by default connect to the backend on port 4000 when you start both servers. the backend connection URL is present on the .env file present in the frontend repo

**Comment by fenil29** [comment]
Sure,
Could you explain what you want to do exactly?

**Comment by fenil29** [comment]
you can follow this guide https://docs.mongodb.com/guides/server/install/ to install MongoDB on your machine.
After that, you just need to change DATABASEURL in the environment variable.

**Comment by KanishJain2** [comment]
I have installed Mongodb Compass on my system. From where do I get the DATABASEURL from that?

**Comment by fenil29** [comment]
it a combination of your username, password, your host in your case its localhost, and the name of the cluster.
https://docs.mongodb.com/manual/reference/connection-string/

**Comment by KanishJain2** [comment]
So can you please help me creating a local host database?
Im just new to this and not able to get how to make the link?
